export enum modal {
  CREATE_PACK = 'CREATE_PACK',
  CREATE_CARD = 'CREATE_CARD',
  UPDATE_PACK = 'UPDATE_PACK',
  UPDATE_CARD = 'UPDATE_CARD',
  DELETE_PACK = 'DELETE_PACK',
  DELETE_CARD = 'DELETE_CARD',
}
